$axure.loadCurrentPage({
  "url":"档案永久删除.html",
  "generationDate":new Date(1385953513608.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"FileName",
"hl"],
  "page":{
    "packageId":"a68204f29da24a749cbf884f0a6074bd",
    "type":"Axure:Page",
    "name":"档案永久删除",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});