$axure.loadCurrentPage({
  "url":"人事档案查询.html",
  "generationDate":new Date(1385953513584.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"FileName",
"hl"],
  "page":{
    "packageId":"dac1c1b6e23b4c30be2d6a7f36035e09",
    "type":"Axure:Page",
    "name":"人事档案查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});