$axure.loadCurrentPage({
  "url":"薪酬管理设置.html",
  "generationDate":new Date(1385360529761.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"FileName"],
  "page":{
    "packageId":"eed9c7491aaf4b54a070a8dec889f3f2",
    "type":"Axure:Page",
    "name":"薪酬管理设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});