$axure.loadCurrentPage({
  "url":"人事档案删除管理.html",
  "generationDate":new Date(1385953513593.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"FileName",
"hl"],
  "page":{
    "packageId":"f86326452e21424ab244124451ea9af2",
    "type":"Axure:Page",
    "name":"人事档案删除管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});