$axure.loadCurrentPage({
  "url":"培训考核与反馈.html",
  "generationDate":new Date(1385444189696.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"FileName",
"hl"],
  "page":{
    "packageId":"3ef5cb73dfd54ced9bcda78abcff7402",
    "type":"Axure:Page",
    "name":"培训考核与反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});