$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1386122826296.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"FileName",
"hl"],
  "page":{
    "packageId":"1ca2e3e401c747b4b8e81005fac69ef3",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0182b9364361411cb23ba4d63ba400d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":9},
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"952a83133cc74726a8246f263ac713f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":9},
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"f30e2018ed2b4d8299fa1924d8c15771",
          "label":"Styled Button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseDown":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF006699},
{
                      "color":0xFF006699}]}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFF666666},
{
                      "color":0xFF666666}]},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF99CCFF},
{
                  "color":0xFF99CCFF},
{
                  "color":0xFF0277BA},
{
                  "color":0xFF0277BA}]},
            "location":{
              "x":286,
              "y":399},
            "size":{
              "width":153,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e393aad63b74c29a13dbb6334464738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseDown":{
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF0099FF},
{
                          "color":0xFF0099FF},
{
                          "color":0xFF006699},
{
                          "color":0xFF006699}]}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFF666666},
{
                          "color":0xFF666666}]},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF99CCFF},
{
                      "color":0xFF99CCFF},
{
                      "color":0xFF0277BA},
{
                      "color":0xFF0277BA}]},
                "location":{
                  "x":286,
                  "y":399},
                "size":{
                  "width":153,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 待办列表",
                      "target":{
                        "targetType":"page",
                        "url":"tonext",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/styled_button_u2.png",
            "mouseDown~":"images/登录/styled_button_u2_mouseDown.png",
            "disabled~":"images/登录/styled_button_u2_disabled.png"}},
{
          "id":"a3fdb9b1a7c34644a76efcec317ee25f",
          "label":"Styled Button",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseDown":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF006699},
{
                      "color":0xFF006699}]}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFF2F2F2},
{
                      "color":0xFFF2F2F2},
{
                      "color":0xFF666666},
{
                      "color":0xFF666666}]},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF99CCFF},
{
                  "color":0xFF99CCFF},
{
                  "color":0xFF0277BA},
{
                  "color":0xFF0277BA}]},
            "location":{
              "x":593,
              "y":399},
            "size":{
              "width":153,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e43dcb35185e4b85b016de5d94112a45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseDown":{
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF0099FF},
{
                          "color":0xFF0099FF},
{
                          "color":0xFF006699},
{
                          "color":0xFF006699}]}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFF666666},
{
                          "color":0xFF666666}]},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF99CCFF},
{
                      "color":0xFF99CCFF},
{
                      "color":0xFF0277BA},
{
                      "color":0xFF0277BA}]},
                "location":{
                  "x":593,
                  "y":399},
                "size":{
                  "width":153,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/styled_button_u2.png",
            "mouseDown~":"images/登录/styled_button_u2_mouseDown.png",
            "disabled~":"images/登录/styled_button_u2_disabled.png"}},
{
          "id":"b3ce35912ff84e38a1f2bdf3f3ba43b5",
          "label":"textfield",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":381,
              "y":282},
            "size":{
              "width":226,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"f6bfccd158694de5a212aaca4d12b027",
          "label":"textfield",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":381,
              "y":335},
            "size":{
              "width":226,
              "height":32}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "0182b9364361411cb23ba4d63ba400d7":{
      "scriptId":"u0"},
    "952a83133cc74726a8246f263ac713f1":{
      "scriptId":"u1"},
    "f30e2018ed2b4d8299fa1924d8c15771":{
      "scriptId":"u2"},
    "3e393aad63b74c29a13dbb6334464738":{
      "scriptId":"u3"},
    "a3fdb9b1a7c34644a76efcec317ee25f":{
      "scriptId":"u4"},
    "e43dcb35185e4b85b016de5d94112a45":{
      "scriptId":"u5"},
    "b3ce35912ff84e38a1f2bdf3f3ba43b5":{
      "scriptId":"u6"},
    "f6bfccd158694de5a212aaca4d12b027":{
      "scriptId":"u7"}}});