$axure.loadCurrentPage({
  "url":"薪酬发放登记明细.html",
  "generationDate":new Date(1385370046727.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"FileName"],
  "page":{
    "packageId":"9af0639deee24f9d90169b311f4868f6",
    "type":"Axure:Page",
    "name":"薪酬发放登记明细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});