$axure.loadCurrentPage({
  "url":"新页面_1.html",
  "generationDate":new Date(1385370046735.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"FileName"],
  "page":{
    "packageId":"7e7994eb9dca43f3beae0d16d5d8b724",
    "type":"Axure:Page",
    "name":"新页面 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});